name: CI/CD

on:
  push:
    branches: [ "main" , "develop" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Read Version
        id: check_version
        run: |
          # Extract version, strip build number (+), remove carriage returns, and trim whitespace
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version:[[:space:]]*//' | cut -d'+' -f1 | tr -d '\r' | xargs)

          if [ -z "$VERSION" ]; then
            echo "âŒ Failed to parse version from pubspec.yaml"
            exit 1
          fi

          echo "Detected version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create Git tag
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          TAG_NAME="v${{ steps.check_version.outputs.version }}"
          git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --no-pub --coverage

      - name: Build Web
        run: flutter build web --wasm --pwa-strategy=offline-first  --base-href "/"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/web'
      - name: Deploy to GitHub Pages
        if:  ${{ github.ref == 'refs/heads/main' }}
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build release APK
        run: flutter build apk --release

      - name: Create GitHub Release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.check_version.outputs.version }}
          name: Release v${{ steps.check_version.outputs.version }}
          draft: false
          prerelease: ${{ github.ref == 'refs/heads/develop' }}
          generate_release_notes: true
          files: |
            build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
